[package]
name = "parser_sqm"
version.workspace = true
edition.workspace = true

[dependencies]
hemtt-sqm = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[lints.rust]
dead_code = "allow"
unused_parens = "allow"
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"

[[bench]]
name = "query_benchmarks"
harness = false