[package]
name = "arma3_tool_report_writer"
version.workspace = true
edition.workspace = true

[dependencies]
arma3_tool_dependency_scanner = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
prettytable = "0.10.0"