[package]
name = "arma3_tool"
version = "0.1.0"
edition = "2021"
description = "A tool for analyzing Arma 3 missions and game data"
authors = ["Tom Campbell <tyen901@gmail.com>"]

[dependencies]
extraction = { path = "../extraction" }
gamedata_scanner = { path = "../gamedata_scanner" }
mission_scanner = { path = "../mission_scanner" }
pbo_tools = { path = "../pbo_tools" }

# Additional dependencies
anyhow = "1.0.97"
clap = { version = "4.5.30", features = ["derive"] }
env_logger = "0.11.7"
indicatif = { version = "0.17.11", features = ["rayon"] }
log = "0.4.26"
num_cpus = "1.16.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
tempfile = "3.18.0"
thiserror = "2.0.11"
tokio = { version = "1.44.1", features = ["full"] }
walkdir = "2.5.0"

[[bin]]
name = "arma3_tool"
path = "src/main.rs"

[[example]]
name = "basic_scan"
path = "examples/basic_scan.rs"

[lints.rust]
dead_code = "allow"
unused_parens = "allow"
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
