[package]
name = "arma3_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
code_scanner = { path = "../code_scanner" }
extraction = { path = "../extraction" }
mission_scanner = { path = "../mission_scanner" }
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.11.6"
indicatif = { version = "0.17.11", features = ["rayon"] }
log = "0.4.26"
log4rs = { version = "1.3.0", features = ["file_appender", "pattern_encoder", "yaml_format"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
test-case = "3.3.1"
tempfile = "3.17.1"

[lints.rust]
dead_code = "allow"
unused_parens = "allow"
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
