[package]
name = "arma3-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
arma3_tool_pbo_cache = { workspace = true }
arma3_tool_report_writer = { workspace = true }
arma3_tool_shared_models = { workspace = true }
arma3_db = { workspace = true }

gamedata_scanner = { path = "../gamedata_scanner" }
mission_scanner = { path = "../mission_scanner" }

anyhow = { workspace = true }
clap = { workspace = true }
petgraph = "0.7.1"
chrono = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }
once_cell = "1.21.1"
rfd = "0.15.3"
lazy_static = "1.5.0"

[workspace]
members = [
    "shared_models",
    "pbo_cache",
    "arma3_db",
    "report_writer",
]

[[bin]]
name = "arma3_tool"
path = "src/main.rs"

[[bin]]
name = "arma3tool_cli"
path = "src/bin/arma3tool_cli.rs"

[[bin]]
name = "arma3tool_ui"
path = "src/bin/arma3tool_ui.rs"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tom Campbell <tyen901@gmail.com>"]

[workspace.dependencies]
# Internal crates
arma3_tool_shared_models = { path = "./shared_models" }
arma3_tool_cache_storage = { path = "./cache_storage" }
arma3_tool_report_writer = { path = "./report_writer" }
arma3_tool_pbo_cache = { path = "./pbo_cache" }
arma3_db = { path = "./arma3_db" }
pbo_tools = { path = "../pbo_tools" }

# External dependencies
anyhow = "1.0.97"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.32", features = ["derive"] }
dashmap = "6.1.0"
env_logger = "0.11.7"
log = "0.4.27"
num_cpus = "1.16.0"
prettytable-rs = "0.10.0"
rayon = "1.10.0"
rmp-serde = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strsim = "0.11.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
walkdir = "2.5.0"
serde_yaml = "0.9.27"
directories = "5.0.1"
tempfile = "3.19.1"

# [lints.rust]c
# dead_code = "allow"
# unused_parens = "allow"
# unused_imports = "allow"
# unused_variables = "allow"
# unused_mut = "allow"

# [profile.release]
# lto = true
# strip = true
# incremental = false
# panic = "abort"