refresh_rate: 30 seconds

appenders:
  # Console appender for all logs
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] [{T}] {m}{n}"

  # Main log file for all logs
  main_file:
    kind: file
    path: "logs/arma3_tool.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] [{T}] {m}{n}"

  # Specific log file for PBO scanning
  pbo_scan:
    kind: file
    path: "logs/pbo_scan.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] {m}{n}"

  # Specific log file for class scanning
  class_scan:
    kind: file
    path: "logs/class_scan.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] {m}{n}"

  # Specific log file for mission scanning
  mission_scan:
    kind: file
    path: "logs/mission_scan.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] {m}{n}"

  # Specific log file for dependency analysis
  dependency_analysis:
    kind: file
    path: "logs/dependency_analysis.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] {m}{n}"

  # Error log file for all errors
  error_file:
    kind: file
    path: "logs/error.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{h({l}):<5}] [{T}] {m}{n}"
    filters:
      - kind: threshold
        level: error

root:
  level: info
  appenders:
    - stdout
    - main_file
    - error_file

loggers:
  # PBO scanning logs
  arma3_tool::scanning::pbo:
    level: info
    appenders:
      - pbo_scan
    additive: true

  # Class scanning logs
  arma3_tool::scanning::classes:
    level: info
    appenders:
      - class_scan
    additive: true

  # Mission scanning logs
  arma3_tool::scanning::missions:
    level: info
    appenders:
      - mission_scan
    additive: true

  # Dependency analysis logs
  arma3_tool::manager:
    level: info
    appenders:
      - dependency_analysis
    additive: true 