[package]
name = "arma3-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
arma3-errors = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }