[package]
name = "arma3-tool-cache-storage"
version.workspace = true
edition.workspace = true

[dependencies]
arma3-tool-models = { path = "../models" }
rmp-serde.workspace = true
serde.workspace = true
chrono.workspace = true
thiserror.workspace = true
log.workspace = true 