[package]
name = "arma3_tool_cache_storage"
version.workspace = true
edition.workspace = true

[dependencies]
arma3_tool_shared_models = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }