[package]
name = "arma3-errors"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }